### ISSUE TITLE
Codeception\Extension\MultiDb Not Defined

### ISSUE THREAD

**Issue by drmmr763** [redmatter/Codeception-MultiDb#19]
Hi There

Thank you for contributing this extension. It is something I will definitely be needing to complete some tests for my project. 

I'm having trouble initializing a simple test to get off the ground with this module. Some basic info:

Composer.json:

```
{
    "require": {
        "codeception/codeception": "^2.1",
        "redmatter/codeception-multidb": " ~2.0@dev"
    }
}
```

Here's my configurations:

acceptance.suite.yml

```
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: 'http://dev.mysite..net'
            port: 5454
            browser: phantomjs
            window_size:  1248x900
            capabilities:
              javascriptEnabled: true
              browserConnectionEnabled: true
              elementScrollBehavior: true
        - \Helper\Acceptance
        - Codeception\Extension\MultiDb
    config:
        Codeception\Extension\MultiDb:
          connectors:
            Primary:
              dsn: 'mysql:host=x.y;dbname=db1'
              user: 'myUser'
              password: 'myPass'
              populate: false
              cleanup: false
            Secondary:
              dsn: 'mysql:host=x.y;dbname=db2'
              user: 'myUser'
              password: 'myPass'
              populate: false
              cleanup: false
```

codeception.yml

```
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
      - Codeception\Extension\RunFailed
      - Codeception\Extension\MultiDb
```

My test is pretty simple:

``` php
/**
     *
     *
     * @param FunctionalTester $I
     */
    public function checkForTemp(\AcceptanceTester $I)
    {
        $I->amConnectedToDb('Secondary');

        $I->seeInDatabase('leads', array(
            'first_name'   => 'Miles',
            'last_name'    => 'Davis',
            'phone_number' => 8788675309
        ));
    }
```

I've tried a number of different things to fix the issue like doing `composer dump-autoload` and `composer install`.

I've also tried working in the `_bootstrap.php` file to add a class autoload per the Codeception documents here (http://codeception.com/docs/reference/Autoload#CodeceptionUtilAutoload)

I wasn't successful in doing that. 

I am using Codeception 2.1 which I know is new / beta per your readme here. 

Any ideas on how I can get this module working?
